### ISSUE TITLE
Cannot have `application/json` and `x-www-form-urlencoded` media types using the same schema

### ISSUE THREAD

**Issue by mefellows** [pactflow/swagger-mock-validator#71]
See repro here: https://github.com/pactflow/bdct-oas-examples/pull/1/files

```
 npx @pactflow/swagger-mock-validator@latest ./examples/forms/forms.oas.yml examples/forms/forms.pact.json
```

Produces:

```
Mock file "examples/forms/forms.pact.json" is not compatible with spec file "./examples/forms/forms.oas.yml"
1 error(s)
	request.body.incompatible: 1
0 warning(s)
{
  warnings: [],
  errors: [
    {
      code: 'request.body.incompatible',
      message: 'Request body is incompatible with the request body schema in the spec file: must be object',
      mockDetails: {
        interactionDescription: 'a request to create a new animal with x-www-form-urlencoded data',
        interactionState: '[none]',
        location: '[root].interactions[0].request.body',
        mockFile: 'examples/forms/forms.pact.json',
        value: 'name=Scratchy&genus=Cat&owner=Cat%20Lady'
      },
      source: 'spec-mock-validation',
      specDetails: {
        location: '[root].paths./animals.post.requestBody.content.application/x-www-form-urlencoded.schema.type',
        pathMethod: 'post',
        pathName: '/animals',
        specFile: './examples/forms/forms.oas.yml',
        value: 'object'
      },
      type: 'error'
    }
  ]
}

Error: Mock file "examples/forms/forms.pact.json" is not compatible with spec file "./examples/forms/forms.oas.yml"
    at _callee$ (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/cli.js:3535:36)
    at tryCatch (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/swagger-mock-validator-10VEx_XP.js:250:16)
    at Generator.<anonymous> (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/swagger-mock-validator-10VEx_XP.js:338:17)
    at Generator.next (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/swagger-mock-validator-10VEx_XP.js:279:21)
    at asyncGeneratorStep (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/swagger-mock-validator-10VEx_XP.js:28:17)
    at _next (file:///Users/matthew.fellows/.npm/_npx/102906fda511f716/node_modules/@pactflow/swagger-mock-validator/dist/swagger-mock-validator-10VEx_XP.js:42:9)
```

Removing the `application/json` results in a passing test.

**Comment by mefellows** [comment]
Fixed by #72
